definitions:
  helpers.Response:
    properties:
      data:
        type: object
      errors:
        type: object
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      operationId: Login
      parameters:
      - description: User credentials
        in: formData
        name: username
        required: true
        type: string
      - description: User credentials
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Provides a JSON Web Token
      tags:
      - Authorization
  /auth/register:
    post:
      operationId: Register
      parameters:
      - description: User credentials
        in: formData
        name: name
        required: true
        type: string
      - description: User credentials
        in: formData
        name: username
        required: true
        type: string
      - description: User credentials
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helpers.Response'
      summary: Register User for Authenticates
      tags:
      - Authorization
  /user/profile:
    get:
      operationId: Profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - ApiKeyAuth: []
      summary: Showing Data User Actived
      tags:
      - Profile
    put:
      operationId: Update Profile
      parameters:
      - description: User credentials
        in: formData
        name: id
        required: true
        type: integer
      - description: User credentials
        in: formData
        name: name
        required: true
        type: string
      - description: User credentials
        in: formData
        name: username
        required: true
        type: string
      - description: User credentials
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helpers.Response'
      security:
      - ApiKeyAuth: []
      summary: Update Profile User Actived
      tags:
      - Profile
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
